services:
  mariadb:
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
  node:
    build: .
    environment:
      # DB_HOST here overrides DB_HOST in .env so that node container connects to mariadb container
      DB_HOST: "mariadb"
    ports:
      - "4000:${PORT}"
    depends_on:
      - "mariadb"

networks:
  default:
    name: stubook

